### ISSUE TITLE
EtcHash on amd miners

### ISSUE THREAD

**Issue by appsettings** [RainbowMiner/RainbowMiner#1273]
Can etchash support be added also on amd miners, like PhoenixMiner and Teamred? And also to 4gb gpu?
https://github.com/eth-classic/etchash
Thanks

**Comment by RainbowMiner** [comment]
Sure, I'll check it.

**Comment by appsettings** [comment]
Thanks, i updated to the new version but i do not see etchash listed on the algo list (from web and from console).
I'm using a rig with 6 rx570 4gb gpu. Zombie mode is enabled.

**Comment by appsettings** [comment]
I tried to check many settings and my setup, but i cannot find what's wrong and why etchash still does not appear as an available algo on all my AMD 4gb rigs.
I does show up on NVIDIA 8gb rigs.
Should it be working also on 4gb?

**Comment by RainbowMiner** [comment]
Hi, sorry for my late answer. I have found a condition, that could eventually use the wrong DAG size. I will fix this asap.

**Comment by RainbowMiner** [comment]
It is fixed now. A new release will be out soon.

**Comment by appsettings** [comment]
Still does not show up to me, i cannot understand why. It doesn't benchmark either. Algo is enabled, it should use zergpool and mrr as pools. With zombie mode ethash is listed correctly and also mrr rig is active, but not with etchash.
I see this behaviour on 3 rigs, all with amd rx 570-580 4gb, using phoenix (usually).
I tried to see if the Test-VRAM function does return a proper value, and also tried to write-log the minmemgb value on phoenix miner file, but they seems correct. I also do not have any errors on the log, it seems that is etchash is filtered out somehow.
Just tell me if I can try any other modifications to find out the problem. Thanks

**Comment by RainbowMiner** [comment]
If you check the http://localhost:4000 of one of these machines, is the Etchash listed for ZergPool in the "Pools" section? If yes, please click the "+" and copy-n-paste the contents of the data here.

Also, please create a "Debug file" and upload it here. I really want to go to the bottom of this.

**Comment by appsettings** [comment]
![image](https://user-images.githubusercontent.com/75400205/101878572-19da5300-3b90-11eb-890d-4ef7a27de6ac.png)

I confirm that etchash is never listed.

Thanks

**Comment by RainbowMiner** [comment]
Ok, so it is most probably not the miner but the pool selection. Could you please create and upload a "Debug file"?
Just click on "Debug file" @ http://localhost:4000

**Comment by RainbowMiner** [comment]
I just had an idea. Look at the TTF and last block found values at ZergPool.

I could be, that ETC is disabled, due to one of the following constraints:
- **MaxAllowedLuck** if luck (= time_since_last_block / time_to_find_one_block) is greater than that number, increase the penalty up to 100% (0=disable, inactive for solo pools) [default=3]
- **MaxTimeSinceLastBlock** if time_since_last_block is greater than that number, increase the penalty up to 100% (0=disable, time-units allowed in input, inactive for solo pools) [default=12h]

**Comment by appsettings** [comment]
OMG i feel so stupid... I realized I had ETC in the list of excluded coins, in config.txt .... now I remember that I set it when there wasn't yet the dag file check.
I apologize for wasting your time, I clearly checked almost all settings but not that one.
I removed it and everything started to work properly. Thanks again

**Comment by RainbowMiner** [comment]
You are welcome. I am happy, that we found the cause.
