### ISSUE TITLE
Feature Request - Manual Reboot

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1461]
Can we get a manual "Reboot Server" button added to our web consoles?

This will help if we're tied up with other things and need to do a simple reboot, without having to putty / remote in.

**Comment by RainbowMiner** [comment]
Sure - I'll add that button.

**Comment by RainbowMiner** [comment]
Ok, added:
- add Reboot button to localhost. To be able to reboot, you must set `"EnableRestartComputer": "1",` in config.txt first. This is a security measure - make sure the web-access to your machine is protected (set some `"APIUser"` and `"APIPassword`" in config.txt). Otherwise everybody with knowledge to your IP can reboot your rig. (issue #1461)

**Comment by saki2fifty** [comment]
Thx!

**Comment by astronyu** [comment]
@RainbowMiner , about "RestartComputerHours": 0.0" what does that means. Does it means I can set it to 120 and it will reboot my rig every 5 days?

**Comment by RainbowMiner** [comment]
@astronyu exactly. 120h / 24h = 5 days

**Comment by astronyu** [comment]
> @astronyu exactly. 120h / 24h = 5 days
> 
> Remember: for reboots to happen, you need to set `"EnableRestartComputer": "1",` in config.txt

Thanks for confirming that. Weird enough, I've already have "EnableRestartComputer": "1" in config.txt and "RestartComputerHours": 0.0".

**Comment by RainbowMiner** [comment]
It's on the Dashboard on http://localhost:4000 - I will add reboot to rbminer.net, too. But therefor we need some kind of PIN or Password to protect us from malicious reboots from people, who know our rbminer.net status report key.

**Comment by astronyu** [comment]
I honestly don't see any button apart from the usual Pause and Lock buttons. I do have user name and password set for the API. Is the button hidden if I set to auto reboot in X hours? If so, maybe good idea to still show the button for on demand reboot.

**Comment by RainbowMiner** [comment]
You need to update to v4.6.9.8

**Comment by astronyu** [comment]
Thank you! I did a manual update and the button is there.

**Comment by saki2fifty** [comment]
Confirmed this morning, button is there!

Also, not sure what core update you've recently applied, but 16 hours uptime on each of my rigs.  Has never got past 2 hours hence, the need for a reboot button!  🥇

**Comment by saki2fifty** [comment]
Well, after attempting to reboot my rigs multiple times, they did not reboot.  (Going off the Uptime status, constant ping, and putty session).  Gave it about an hour.

Linux server.  Launching RBM screen as a service upon boot if that makes a diff.  (RBM.service).

**Comment by RainbowMiner** [comment]
> Linux server. Launching RBM screen as a service upon boot if that makes a diff. (RBM.service).

Which Linux distro are you running?

**Comment by saki2fifty** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by RainbowMiner** [comment]
Ok, I'll look into it. I have some 18.04 machines, as well.

**Comment by saki2fifty** [comment]
Thx!

My exact service:

[Unit]
Description=RainbowMiner
After=network.target
StartLimitIntervalSec=0
[Service]
Type=forking
Restart=always
RestartSec=1
User=root
ExecStart=/usr/bin/screen -S RainbowMiner -d -m /home/[user]/RainbowMiner/start.sh
#ExecStart=/home/[user]/RainbowMiner/start-nohup.sh

**Comment by RainbowMiner** [comment]
Ok, that last commit 2aa9c84dbc6cf1f37c68092e891a147228064da5 should solve the Linux reboot issue.

**Comment by saki2fifty** [comment]
Still does not reboot, but...  Noticed Include.psm1 did not get the code change.

How do I properly pull recent commits?

**Comment by RainbowMiner** [comment]
Two ways possible for an update:
- either wait for a release and use the update function of RainbowMiner
- or download the current [master.zip](https://github.com/RainbowMiner/RainbowMiner/archive/master.zip) and extract it right into your RainbowMiner folder with overwrite all files. Your configuration will not be touched.

Just in case, could you please create a Debug file and upload it here? Just open http://localhost:4000 in your browser and click "Debug file". It will create a zip file containing the logs of the past three days plus a condensed configuration record. All sensible data (like wallets, passwords, api data) will be XXXed out.

**Comment by saki2fifty** [comment]
I was actually about to manually download and extract, then had to head out.  I assumed you queue up your fixes before you release...  was going to wait for it, but thought I'd ask.

Attached.  One rig:
[debug_2021-03-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/6095789/debug_2021-03-06.zip)

**Comment by saki2fifty** [comment]
Confirmed to work on v.4.6.9.9.

Thx,

**Comment by astronyu** [comment]
@RainbowMiner , is it possible to also have this feature enabled for remote miners? Instead of having to open a separate dashboard for other miner, can we instead reboot that particular rig from server/main rig? Don't know where the best place to put this additional button but maybe an extra button in console tab would do?
