### ISSUE TITLE
Issue: Errors

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#185]
Just updated Rainbow and Azure powershell 6.9. Now errors.

![image](https://user-images.githubusercontent.com/42227809/46261917-3017ff00-c4af-11e8-838e-1b4ecf2becf9.png)

![image](https://user-images.githubusercontent.com/42227809/46261925-63f32480-c4af-11e8-9c3e-e0d9df2bbea4.png)

**Comment by Byrd1083** [comment]
[RainbowMiner_2018-09-30.txt](https://github.com/RainbowMiner/RainbowMiner/files/2431955/RainbowMiner_2018-09-30.txt)
[RainbowMiner_2018-09-30_12-44-35.txt](https://github.com/RainbowMiner/RainbowMiner/files/2431956/RainbowMiner_2018-09-30_12-44-35.txt)

**Comment by Byrd1083** [comment]
Repaird powershell. says version 5.3. Still funny errors when switching happens.

![image](https://user-images.githubusercontent.com/42227809/46262054-de707400-c4b0-11e8-9890-d868990ec49e.png)

**Comment by RainbowMiner** [comment]
Oh :) What the heck.. o, it is a warning only, but a lengthy. I will correct it at once.

**Comment by RainbowMiner** [comment]
Should be fixed with v3.8.8.3

**Comment by RainbowMiner** [comment]
I am not so sure, what caused this misbehaviour, since I do not have this problem, here. I suspect a SSL problem with the powershell invoke function. Please keep me updated, if everything works fine now.

**Comment by hernandn01** [comment]
still the same error after updating to 3.8.8.3 and I do not see that my miner updates the monitoring page
https://rbminer.net/monitoring/?user=cb5082f8-434f-4aee-bdbe-fd01023cf02e

**Comment by RainbowMiner** [comment]
Ok. Found it. I forgot to update the Core.psm1. It called the old report status ps1. Now everything will work.
Sorry for this!

**Comment by hernandn01** [comment]
working fine after 3.8.8.4. No warning and monitoring page

**Comment by RainbowMiner** [comment]
Yeah! :)

**Comment by Byrd1083** [comment]
It also throws a red lettered error when switching. However, it flash so fast that I can not catch it with a screen shot.

**Comment by Byrd1083** [comment]
[RainbowMiner_2018-09-30.txt](https://github.com/RainbowMiner/RainbowMiner/files/2432177/RainbowMiner_2018-09-30.txt)
[RainbowMiner_2018-09-30_16-39-50.txt](https://github.com/RainbowMiner/RainbowMiner/files/2432178/RainbowMiner_2018-09-30_16-39-50.txt)

**Comment by Byrd1083** [comment]
All I can read is red letters and the word configuration stands out.

**Comment by RainbowMiner** [comment]
Is there a special reason, that you want to install azure-powershell 6.9? I do not know if this is compatible with RainbowMiner. If in doubt, I would better install the not-azure powershell 6.1, using the installer I posted above.
