### ISSUE TITLE
FLUX prices appear way off in RBM Rate Conversion Table

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1904]
The FLUX rates shown in RBM’s rate conversion table appear to be off by more than 50%.  The RBM table currently shows them shows them as $0.9146 / 0.01892 mBTC, while CoinMarketCap shows them as $1.60 / 0.03298 mBTC.

I was wondering why FLUX was never showing up near the top of RBM’s profitability rankings for my 2080 rig, when it was frequently showing up near the top of WhatToMine’s and other sites’ rankings for 2080 rigs.  I think the incorrect rate is at least part of the reason.  Another possibility is that RBM is not taking account of the parallel assets paid when mining FLUX, currently an added +39% bonus on MinerPool (paid in FLUX), and it looks like the bonus will be increasing in the future with additional parallel assets.

I have been trying out RBM for a few days now and I am impressed.  Thanks for your efforts!  I would appreciate it if you would look into the FLUX issue.

**Comment by RainbowMiner** [comment]
Thank you for reporting! I will check FLUX. It's most probably as you say, that we don't account for the bonus payments.

**Comment by coolbreeze21** [comment]
WhatToMine says that they account for the bonus rewards in FLUX ("Bonus rewards included by default"), but I think RBM may use a different data source.  If so, you could use WTM for comparison.  The current bonus rate is +39% and it looks like it is on its way to +78% soon, so it is a big difference in profitability.  MinerPool.org is currently the #1 FLUX pool and they make it easy by automatically converting and paying all the parallel assets in FLUX to the miner's main wallet.

Is it a viable workaround to set the penalty on FLUX in coins.config.txt to -39% or some other appropriate number?  Or does that cause other issues?  RBM appears to accept a negative penalty for coins as a valid entry.  If so, what is the correct value to reflect 39% rewards?  I am not sure how how the percentage is applied.

It still looks to me like the base FLUX rate is off by around 57% (vs. CoinMarketCap), apart from the parallel assets issue.  I have checked this on two rigs running independently.  Thanks for the quick follow up!

**Comment by RainbowMiner** [comment]
That's correct: a negativ penalty will increase the profit calculation. It's handled via an internal factor: `Profit = BaseProfit * (1 - Penalty/100)`

**Comment by RainbowMiner** [comment]
Ok, I have found the main culprit - we used the wrong FLUX coin. It should be fixed now.

**Comment by coolbreeze21** [comment]
The RBM Rate Conversion Table now appears to be correct here on 2 rigs.  Thanks a lot!

I am going to give it a little time to see what, if any, issues remain (i.e. parallel asset bonuses) after the rate fix has had a chance to flow through all the calculations.

I am very relieved that my first ever posting on GitHub wasn't some stupid newbie mistake.  Whew!

**Comment by RainbowMiner** [comment]
I have update the Minerpool module, so that it now accounts for the parallel asset bonuses. Thanks again for reporting this.

**Comment by coolbreeze21** [comment]
I have tried to force RBM to connect to MinerPool (boosted the FLUX penalty to -90%, disabled all other FLUX pools), but it refuses to do so, even though it shows EquihashR (125,4) as the most profitable algo under Miners and MinerPool as the most profitable Flux pool under Pools.

I think the problem may be that the RBM pools info shows the host as “na.minerpool.org” while MinerPool says that for FLUX it should be “flux-us.minerpool.org” (substitute “eu” or “asia” for “us” in the EU or Asia).  The port for most rigs should be 2033 (2032 for < 1070Ti or < 50 sol/s).  I couldn’t figure out where to change that setting myself.  Did I miss something?

**Comment by RainbowMiner** [comment]
So far - I had to work a little more on that topic. From now on, the values for all FLUX pools should reflect the correct profits.

**Comment by coolbreeze21** [comment]
After giving the earlier changes some time to take effect, I found that I still needed to add around a -33% penalty (bonus) to FLUX coin to get the RBM profitability estimates for FLUX on MinerPool close to the WTM and MinerPool estimates.  Do I need to wait for the next release for some of the code changes to take effect?

Also, what accounts for MinerPool’s poor 51% accuracy rate?  Is it being penalized for paying out 39% more than estimated in the form of parallel assets?  That wouldn’t seem right.

**Comment by RainbowMiner** [comment]
> Also, what accounts for MinerPool’s poor 51% accuracy rate? Is it being penalized for paying out 39% more than estimated in the form of parallel assets? That wouldn’t seem right.

That's because I have updated the prices. It will slowly adapt, but you can speed it up: just delete all `WhatToMine_*_Profit.txt` files in `.\Stats\Pools`

**Comment by RainbowMiner** [comment]
> After giving the earlier changes some time to take effect, I found that I still needed to add around a -33% penalty (bonus) to FLUX coin to get the RBM profitability estimates for FLUX on MinerPool close to the WTM and MinerPool estimates. Do I need to wait for the next release for some of the code changes to take effect?

Yes, better wait for the next release (will be publishe in aprox. 1 hour)

**Comment by coolbreeze21** [comment]
So, I waited and my 2080 rig automatically picked up the v4.7.9.5 update about an hour ago, but something still seems way off, even worse than before.  It is now taking a whopping -115% penalty (bonus) to FLUX coin to convince RBM to mine FLUX on MinerPool and show a profitability that roughly matches what WTM and MinerPool say it should be (around $2.09 net per day, tied with ETH near the top of the rankings).  Accuracy is now near 100%, since I followed your recommendation to delete the WhatToMine_*_Profit.txt files, so it isn’t that.  The RBM console and MinerPool website are showing that the rig is mining away at the expected 73 H/s and submitting accepted shares, so any connection issues appear to have been addressed successfully, but the RBM profitability calcs are so far off from WTM and Minerpool that I think there has to still be an issue somewhere.

Please take another look at this.  Thanks!

**Comment by coolbreeze21** [comment]
I just noticed that the RBM FLUX rate conversion table has regressed to a wildly inaccurate $0.6873 / 0.01375 mBTC, so that is probably part of the issue, if not the whole issue.  It should be around $1.67 / 0.03343 mBTC according to CoinMarketCap.  It would be nice if that were a quick fix.

**Comment by RainbowMiner** [comment]
Yes, my bad. I found a typo in the online quotes engine. Should be fixed asap. If the rates are back to normal, please delete the WhatToMine_*_Profit.txt files again.

**Comment by coolbreeze21** [comment]
The FLUX rates appear back to normal, so I deleted the WhatToMine_*_Profit.txt files on both of my rigs.  The WhatToMine_Take2_RTM_MST_Profit.txt file promptly regenerated, but none of the other files did, which they had done on the previous deletion.  I am guessing that WhatToMine_EquihashR25x4_FLUX_Profit.txt is pretty important to this issue and it is not being regenerated on either rig after 30 minutes.

Also, 1) FLUX on Minerpool now refuses to start, even when given a FLUX coin bonus that should cause it to start and 2) the MinerPool Accuracy statistic has dropped from near 100% to 63%.
