### ISSUE TITLE
New Dynamo algo and rejected duplicate shares

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1968]
RBM 4.8.0.7 updated SrbminerMulti to v0.9.2.1 which adds the “dynamo” algo.  The SRBminerMulti dev, doktor83, has written “dynamo might be the most profitable thing to mine now on CPU”.  RBM appears to confirm that is correct.

He has also written “dynamo will have a lot of rejected shares with the message 'duplicate share'. That is because everyone is working on the same job. It's not a miner issue”.  This also appears to be true.  Unfortunately, it looks to me like the RBM watchdog notices the high rate of rejected duplicate shares (50% on a 5950X, 80%+ on an i9 9900K) and kicks SrbMinerMulti/dynamo after a while, even though it is still the most profitable CPU miner/algo despite the rejected shares.

Is there a way to configure RBM to be more tolerant of the unusually high, but expected, number of rejected shares in dynamo and not kick it, but just factor the rejected shares into the profitability?

**Comment by coolbreeze21** [comment]
4.8.0.8 looks like a definite improvement.  Do you think that the RBM profitability stat now takes into account the rejected shares for each rig?  I am particularly concerned about the i9-9900K rig, where the CPU mines continually using 116 W of power, but currently has 97% of its shares rejected.  If RBM says it has a profitability of, say, $0.25/day, does that mean $0.25 is the projected profit if only 3% of the submitted shares continue to be accepted going forward, or is that the profitability assuming 100% of submitted shares are accepted?

**Comment by RainbowMiner** [comment]
That's a good question. I am not so sure either. I'll let one test rig run for 24h and verify the result.

**Comment by coolbreeze21** [comment]
That make sense.  Thanks!  My gut feeling was the same, that RBM wasn't factoring in the rejected duplicate shares.  So, with that change, the profitability stats should be roughly correct and comparable to other algos, including electric costs, right?  Do I need to wait for the next release for this change to take effect?

**Comment by RainbowMiner** [comment]
> So, with that change, the profitability stats should be roughly correct and comparable to other algos, including electric costs, right? Do I need to wait for the next release for this change to take effect?

Right and right. I am just on my way pushing a new quick-fix release.

**Comment by coolbreeze21** [comment]
Great!  You probably noticed, but lolMiner 1.45 got released 2 hours ago.

**Comment by RainbowMiner** [comment]
Sure :) I have been waiting with the current release for their Windows compile.

**Comment by coolbreeze21** [comment]
Alas, the ETH+TON algo promptly disappeared from both my rigs with the RBM v4.8.0.9/lolMiner 1.45 update 😢.  It is no longer visible as an algo option in Miners, Active Miners or Benchmarks.  Resetting the Watchdog had no effect.  I still have Rustpool disabled on both rigs, so it isn’t that.  Are you seeing the same thing?

**Comment by RainbowMiner** [comment]
Don't worry! I will check it asap.

**Comment by RainbowMiner** [comment]
The last release v4.8.1.0 should solve the "Alas, the ETH+TON algo promptly disappeared" problem.
Also, the rejected share ratio is now factored into the hashrate of SrbminerMulti's dynamo algorithm. But I am not yet happy with that solution. I will change the adaption in the near future, it feels quiet hard wired, at the moment.

**Comment by coolbreeze21** [comment]
4.8.1.0 did cause ETH+TON to promptly reappear on the 3090 rig.  However, it is still gone on the 2080 rig.  I have tried resetting the watchdog, restarting RBM, and checking the settings, but it is still gone from Miners, Active Miners and Benchmarks.  Is there anything else I can try to get it back, like reinstalling the lolMiner module?

**Comment by RainbowMiner** [comment]
Oh dear! Sorry, I did mess up the fix. Now it should be working.

**Comment by coolbreeze21** [comment]
It looks like 4.8.1.1 did the trick on both rigs 🥂.  Thanks for the major boost in profitability with ETH+TON and Dynamo!

**Comment by jch9678** [comment]
I seem to be still having the problem with Dynamo at zergpool coins.  It should be the most profitable by far, but it disappears.
[debug_2022-02-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/8142260/debug_2022-02-25.zip)

**Comment by coolbreeze21** [comment]
At 11:11 AM EST today (about 40 minutes from now) Dynamo is changing the algo to one that will favor GPUs and supposedly make CPU mining unprofitable.  It may be best to wait a bit for the dust to settle from the algo switch.  I also mine dynamo at zergpool and could offer some explanations/advice, but it would probably be rendered obsolete within an hour.

**Comment by jch9678** [comment]
Oh thank you.  I just updated RM to a version that included Dynamo and the benchmark looked great.  What algo is it changing too, I wonder why they are doing?  I'll take a quick look.

**Comment by coolbreeze21** [comment]
I don't have any additional details about the new algo.  It sounds to me like the Dynamo devs freaked out over SrbMiner discovering a way to CPU mine their old algo that was 20 times faster than their in-house miner, turning Dynamo briefly into the most profitable CPU coin (but only if you had a very fast processor, since everyone was trying to mine the same block, hence the duplicate shares).

**Comment by jch9678** [comment]
Looks like it was always supposed to favor gpus, they just goofed on their algo and cpu miner developers found an optimization.

**Comment by coolbreeze21** [comment]
jch9678,

It looks to me like the Dynamo CPU party is over.  The Dynamo dev, Shaun Neal, posted in Discord shortly after the fork that, “39xx and 59xx will still be competative [sic] to mid range GPU”.  My testing with a 5950X since then shows it going from the top to the bottom of the RBM’s CPU profitability rankings.  Perhaps Shaun is right that is competitive with a mid-range GPU on Dynamo.  But GPU mining Dynamo isn’t reported to be nearly as profitable lots of other algos.  I think Dynamo has returned to being a crypto backwater being GPU mined by a few diehard true believers.  Right now, lolminer’s ETH + TON dual-mining code, another recent innovation, looks to be the best GPU algo for better GPUs, though that is fading too as more miners discover it.

This is probably a good time to thank SrbMiner and RainbowMiner for the Dynamo CPU mining party.  Without SrbMiner’s clever code, and RBM’s swift integration of it, I would have missed the bacchanalia.  With innovations like Dynamo CPU mining and ETH + TON, if you snooze, you lose.  I think RainbowMiner deserves enormous credit for so actively developing and updating RBM.  But users have to turn on autoupdates, and accept the resulting benchmarking, to get the benefits of RBM inviting you to 10-day orgies like this.

**Comment by jch9678** [comment]
Haha, thanks for the info.  There will be more orgies.
