### ISSUE TITLE
mining with both amd and nvidia

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2548]
for some reason... maybe its just bzminer... it says its mining with just an AMD card but seems to be using the nvidia ones as well... then another miner opens to mine using the nvidia cards and excluding the amd and it works... but eventually the system freezes up and hangs when one of the miner tries to close and release the cards... or at least i think thats whats happening

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/e895a77a-96a2-4df4-9013-7f920944628d)
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/6ccb1756-d7dc-4acd-8167-3e9b52b4f316)

**Comment by RainbowMiner** [comment]
Yes, mixed rigs can be a hussle. Please upload a Debug file. It's most probably a BzMiner thing.

**Comment by whitindllc** [comment]
its defintely bzminer... i have two wildrigs open and they are running the way they are supposed to...i'll get the debug and just exclude bzminer for now

**Comment by whitindllc** [comment]
[debug_2023-11-28.zip](https://github.com/RainbowMiner/RainbowMiner/files/13494259/debug_2023-11-28.zip)

**Comment by whitindllc** [comment]
so what did you find?

I found an issue with SgminerFancyIX as well... since i just started playing with AMD i dont know if this is isolated to me... but when this miner is running it will take 4 to 6 GB of memory and the pc becomes inoperable.. the second i disabled it via config everything runs fine... even when mining

**Comment by RainbowMiner** [comment]
The BzMiner problem is solved. I will now have a look into the old SgminerFancyIx

**Comment by whitindllc** [comment]
what do you need on my end to help?

**Comment by whitindllc** [comment]
looks like its still an issue on my end.... 
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/39603e0a-10eb-4471-8173-45bcab7c7fc2)

**Comment by RainbowMiner** [comment]
Could you please generate another Debug file with the bzminer commandline in it?

**Comment by Robbylikes** [comment]
Not trying to change topic but how did you get unminable to duel mine zergpool? Do it switch to nicehash with while using unminable? I can't get mine to switch around when other pool combinations are more profitable.

**Comment by whitindllc** [comment]
> Not trying to change topic but how did you get unminable to duel mine zergpool? Do it switch to nicehash with while using unminable? I can't get mine to switch around when other pool combinations are more profitable.

Dont let the profitability numbers fool you.... if there is a coin on 2 pools and one says its making 9.00 a day the other says 1.20 look at the accuracy next to them.... my guess is the 9 dollar one is probably 5% accuracy and the 1.20 is 95% .... thats often why you will see a coin mined on the lower priced on because it is more accurate 

this particular coin set was actually in the benchmarking phase.... i actually didnt do it... RBM did... 
RBM sees that eth is either the most profitable @ zerg or nicehash most of the time... eth/autolykos/octopus/etc are pretty much the main algos you can dual mine with.... i think by default dual mining is turned on in RBM

**Comment by whitindllc** [comment]
here is the command and the debug
Bin\GPU-BzMiner\bzminer.exe -a ironfish --amd 1 -p stratum+tcp://ironfish.auto.nicehash.com:9200 -w 3P4ftijmArHf6HzE2Evw96oSnTLXGg6AKy.NSM1 --pool_password x -r NSM1 -c config_33200.txt --http_enabled 1 --http_address localhost --http_port 33200 --no_watchdog --community_fund 0 --hide_disabled_devices --cpu_validate 0 --nc 1 -o bzminer_33200.log --clear_log_file 1 --oc_enable 0
[debug_2023-12-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/13533507/debug_2023-12-01.zip)

**Comment by RainbowMiner** [comment]
Ok, that localizes the problem pretty good. I'll push a fix.

**Comment by whitindllc** [comment]
hey i found this with nbminer as well.... it tries to pick 0 1 2 instead of 1 2 3.... 0 is an amd card

0  H/s 00d/00h/00m Once    NBminer  KawPOW2g  CLORE RTX A4000  RPlant 0W   Bin\GPU-NBMiner\nbminer.exe --api 127.0.0.1:34001 -d 0,1,2 -o stratum+tcp://stratum-na.rplant.xyz:7083 -u AUUrMrGkFJFB5Mp2x9sqe7D19XAEJB3P13.NSM1 -px --no-watchdog --share-check 0 -a kawpow 164.98 MH/s 

00d/00h/06m Once    SrbMinerMulti SHA3d REDB  RX 5500 XT RPlant 120W  Bin\ANY-SRBMinerMulti\SRBMiner-MULTI.exe --algorithm sha3d --api-enable --api-port 34900 --api-rig-name NSM1 --gpu-id 0 --disable-cpu --disable-gpu-nvidia --disable-gpu-intel --pool stratum-na.rplant.xyz:7076 --wallet rELQCtzYPgt875a5BJTJDXRkgBaR3pd5LN.NSM1 --password x --tls false --nicehash false --keepalive --retry-time 10 --disable-startup-monitor

**Comment by whitindllc** [comment]
sweet let me know when i can test both please
