### ISSUE TITLE
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): 

### ISSUE THREAD

**Issue by Kin39** [RainbowMiner/RainbowMiner#2797]
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:33200))"

What does this error mean? I was mining KCN on MoneroOcean using BzMiner but it did not work.. The dashboard reported 831.69 MH/s but no shared where found...

Thanks

**Comment by whitindllc** [comment]
There was a huge spike in KCN ... i had a few miners waste a whole day mining it on moneroocean... and then i disabled it....
Then all of a sudden it started trying to mine it on ZPOOL which makes ZERO sense since it finds a block ones ever 3 hours or so

**Comment by YastrebX** [comment]
Have the same issue. Just disabled sha3d algo

**Comment by Kin39** [comment]
I disabled sha3d too for now but, the error "Wait" with "1" argument(s): "One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:33200))" is related to many miners on my end.

**Comment by RainbowMiner** [comment]
This problem should be solved now. We had the pre-fork algorithm in our database for KCN.

**Comment by Kin39** [comment]
> This problem should be solved now. We had the pre-fork algorithm in our database for KCN.

Thanks! 

Now only one problem remain: "PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:33200))"

This error appear when using SrbMinerMulti

**Comment by RainbowMiner** [comment]
That `PS>TerminatingError()` error occurs, when a miner software crashes, before RainbowMiner can contact it's API.
To analyse what is happening: can you please show me the full command line of the SrbminerMulti? You can find it in the logs. Alternatively, you could create and upload a Debug file (find it on http://localhost:4000).

**Comment by Kin39** [comment]
Debug File uploaded
[debug_2024-06-09.zip](https://github.com/user-attachments/files/15751126/debug_2024-06-09.zip)

**Comment by Kin39** [comment]
`ANY-SRBMinerMult
                                                                                                       i\SRBMiner-MULTI
                                                                                                       .exe
                                                                                                       --algorithm
                                                                                                       randomxeq
                                                                                                       --pool gulf.mone
                                                                                                       roocean.stream:1
                                                                                                       0256 --wallet 43
                                                                                                       DFJd7pAciiX8rCDa
                                                                                                       gH5R3X8a4hcx5Dzj
                                                                                                       eSYEV2WXnnFMGFFf
                                                                                                       YpxJZXedfTMb7K6k
                                                                                                       9cWJSsV8R36WA1e4
                                                                                                       GvDWAY3HUJFZH
                                                                                                       --password Porco
                                                                                                       diocpu:x~rx/xeq
                                                                                                       --tls false
                                                                                                       --nicehash
                                                                                                       false
                                                                                                       --keepalive
                                                                                                       --retry-time 10
                                                                                                       --disable-startu
                                                                                                       p-monitor
                                                                                                       --disable-gpu
                                                                                                       --cpu-threads
                                                                                                       23
                                                                                                       --cpu-affinity
                                                                                                       0x7fffff
                                                                                                       --api-enable
                                                                                                       --api-port
                                                                                                       34902
                                                                                                       --api-rig-name
                                                                                                       Porcodio --rando
                                                                                                       mx-use-1gb-pages`
