### ISSUE TITLE
TurtleCoin on HeroMiners

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#599]
TurtleCoin does not show up on HeroMiners Balance. Most likely due to the off way they have it implemented. Wanted to see if it can be added.

**Comment by RainbowMiner** [comment]
I will have a look. Please make sure, that both wallets have been added to the pools.config.txt (do NOT use the password field): https://github.com/RainbowMiner/RainbowMiner/issues/597

**Comment by Yamanipanuchi** [comment]
"HeroMiners": {
    "XWP": "",
    "XWP-Params": "",
    "Worker": "$WorkerName",
    "Penalty": 0,

Do I add an additional line here with TRTL?

**Comment by Yamanipanuchi** [comment]
"HeroMiners": {
    "XWP": "",
    "XWP-Params": "",
    "Worker": "$WorkerName",
    "Penalty": 0,
    "Algorithm": "",

Do I add a line below XWP with the wallet address? I already have the wallet added to coins.config.txt. Would I need it in both locations for the balance for TRTL to show up. Balances for other coins show up, Just not TRTL.

**Comment by RainbowMiner** [comment]
Ah, sorry. I saw this a little late.
You may as well rename "XWP" and "XWP-Params" to "TRTL" and "TRTL-Params"

**Comment by RainbowMiner** [comment]
```
"HeroMiners": {
"TRTL": "$TRTL",
"TRTL-Params": "",
"Worker": "$WorkerName",
"Penalty": 0,
"Algorithm": "",
```

**Comment by Yamanipanuchi** [comment]
Ya, I added that. It did work. Notice Fairpool not showing up also. Not sure if its is related or now.

**Comment by RainbowMiner** [comment]
Would you please send me a debug file? I would like to have a look.

**Comment by Yamanipanuchi** [comment]
[debug_2019-07-14 (2).zip](https://github.com/RainbowMiner/RainbowMiner/files/3390500/debug_2019-07-14.2.zip)

so downloading the debug file on linux doesn't work either. pulled this one from a windows client. fairpool balance still does not show up. Ill see if i can manually pull the files and put in a seperatr issue for that.

**Comment by Yamanipanuchi** [comment]
As of right now i cannot get TRTL or XMR to show up on Herominers and i cannot get Fairpool to show up at all.

**Comment by Yamanipanuchi** [comment]
Ok, This is weird... I added EquiHash 192 for 2miners and shortly after 2miners showed up in my balances area. Then about 20 minute later I added RVN and used 2miners also. Then 2miners disappeared from the balances area.?!

**Comment by Yamanipanuchi** [comment]
Both CCX and TRTL I use wallet + payment ID as i am mining to TradeOgre directly. I suspect this is why these balances do not show up.

As for fairpool, non of the balances show up at all.

**Comment by Yamanipanuchi** [comment]
I bet this is it...

2019-07-16 18:01:34 [348.40 343.40] WARNING: [2019-07-16 18:00:43] Problem fetching https://.herominers.com/api/stats using REST: Cannot bind parameter 'Uri'. Cannot convert value "https://.herominers.com/api/stats" to type "System.Uri". Error: "Invalid URI: The hostname could not be parsed."
2019-07-16 18:01:34 [332.27 327.27] WARNING: [2019-07-16 18:00:43] Problem fetching https://.herominers.com/api/stats using REST: Cannot bind parameter 'Uri'. Cannot convert value "https://.herominers.com/api/stats" to type "System.Uri". Error: "Invalid URI: The hostname could not be parsed."
2019-07-16 18:01:34 [332.28 327.27] WARNING: [2019-07-16 18:00:43] Problem fetching https://.herominers.com/api/stats using REST: Cannot bind parameter 'Uri'. Cannot convert value "https://.herominers.com/api/stats" to type "System.Uri". Error: "Invalid URI: The hostname could not be parsed."

Shows three URL's it couldnt get to, And I happen to have three coins that are not showing up.

**Comment by RainbowMiner** [comment]
Ok, now I have time to dig deeper into this. Actually, I already fixed the FairPool balances. But now we need to check, what is going on with herominers on your rigs.
Would you please send me a zip of your Logs folder?

**Comment by RainbowMiner** [comment]
I think, I have solved this issue. Try the new release v4.3.5.9

**Comment by Yamanipanuchi** [comment]
Still do not show up. I am grateful though to the time you put into this! And by this I mean RBM as a whole!

**Comment by RainbowMiner** [comment]
Now it should show up. I have changed the balance modules, so that wallets with payment id will be listed, too.
