### ISSUE TITLE
Time on Pool

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#835]
Sorry for all the suggestions, just spit ballin ideas. On the pool earnings page, it might be useful to be track how long is spent on each pool so that an average earnings per time could be calculated. This way we could see which pool is underperforming.

**Comment by RainbowMiner** [comment]
There is a parameter `"CoinSymbolPBM": "",` in pools.config.txt

If you add a coin to this specific list, that coin will be mined only, if postblockmining conditions apply _or_ if it is the only avail pool for this algorithm.

I think, the second option causes a bit of a problem, if there is only one pool in use, and if that's being used as postblockmining. I will change that in the next release.

**Comment by acos0874** [comment]
Here is my current set up 

`  "ZergPoolCoins": {
    "AECurrency": "",
    "BTC": "$Wallet",
    "BTC-Params": "",
    "Worker": "$WorkerName",
    "Penalty": 10,
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "xzc",
    "ExcludeCoinSymbol": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "1",
    "CoinSymbolPBM": "xzc",
    "DataWindow": "",
    "StatAverage": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": ""`

How do you suggest I change it? If I put xzc in the excludedcoinsymbol it disables pbm as far as I can tell. If I remove xzc from the coinsymbol section it'll end up enabling every single coin.

**Comment by RainbowMiner** [comment]
Your setup is totally correct. But, I suspect, you have ZergPoolCoins as only MTP pool. So this applies:

> or if it is the only avail pool for this algorithm.

.. I will change this ASAP, so that it will idle until PostBlockMining happens, even if it's the only MTP pool.

**Comment by RainbowMiner** [comment]
Done.
With the next release, the parameter `"CoinSymbolPBM"` in pools.config.txt will work as expected, even if there is only one pool for the coin's algorithm selected:

If you put a coin symbol onto the `"CoinSymbolPBM"` list, this coin will idle on the corresponding pool, until the post block mining condition is met.

**Comment by acos0874** [comment]
That would be fantastic thank you

**Comment by acos0874** [comment]
I still can't get this working quite as intended. I have tried several combinations of options in the pools and coins config. You description above...

"If you put a coin symbol onto the "CoinSymbolPBM" list, this coin will idle on the corresponding pool, until the post block mining condition is met."

Is exactly want I want to happen, but unfortunately my miners will still select zcoin, perhaps my settings are incorrect?

  "ZergPoolCoins": {
    "AECurrency": "",
    "BTC": "$Wallet",
    "BTC-Params": "",
    "Worker": "$WorkerName",
    "Penalty": 0,
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "xzc,zel",
    "ExcludeCoinSymbol": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "1",
    "CoinSymbolPBM": "xzc,zel",
    "DataWindow": "",
    "StatAverage": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "15"

  "xzc": {
    "Penalty": "5",
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "Wallet": "",
    "EnableAutoPool": "0",
    "PostBlockMining": "1h",
    "MinProfitPercent": "95",
    "Comment": ""
  },

I should mention my set up is to use nicehash and then zergpool for just zcoin and zelcash, but only mining immediately after a block.
